language: generic

sudo: required
services:
   - docker

before_install:
   - docker build -t  andrea-milan/docker-react -f Dockerfile.dev . 


script:
   - docker run -e CI=true andrea-milan/docker-react npm run test
