language: generic

sudo: required
services:
   - docker

before_install:
   - docker build -t  andrea-milan/docker-react -f Dockerfile.dev . 


script:
   - docker run -e CI=true andrea-milan/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "eu-central-1"
   app: "Docker-React"
   env: "Dockerreact-env"
   bucket_name: "elasticbeanstalk-eu-central-1-430478603437"
   bucket_path: "Docker-React"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
	secure: "$AWS_SECRET_KEY"
