version: '3'
services:
    web:
      build:
         context: .
         dockerfile: Dockerfile.dev
      ports:
         - "3000:3000"
      volumes:
         - /data/frontend/node_modules
         - .:/data/frontend
    tests:
      build:
         context: .
         dockerfile: Dockerfile.dev
      volumes:
         - /data/frontend/nodes_modules
         - .:/data/frontend
      command: ["npm", "run", "test"]
